# REF: https://github.com/goreleaser/example/blob/master/.goreleaser.yaml

version: 2

project_name: doxctl
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates: 
    - "slmingol/doxctl:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/amd64"
  - image_templates: 
    - "slmingol/doxctl:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "slmingol/doxctl:{{ .Tag }}"
    image_templates:
      - "slmingol/doxctl:{{ .Tag }}-amd64"
      - "slmingol/doxctl:{{ .Tag }}-arm64"
  - name_template: "slmingol/doxctl:latest"
    image_templates:
      - "slmingol/doxctl:{{ .Tag }}-amd64"
      - "slmingol/doxctl:{{ .Tag }}-arm64"

brews:
  - repository:
      owner: slmingol
      name: homebrew-tap
    directory: Formula
    homepage: https://www.github.com/slmingol/doxctl
    description: "Software to create fast and easy drum rolls."
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: goreleaser@lamolabs.org
    dependencies:
      - name: go
      - name: coreutils
    test: |
      system "#{bin}/doxctl"
    install: |
      bin.install "doxctl"

